//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/GameMobile/MobileController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MobileController: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MobileController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MobileController"",
    ""maps"": [
        {
            ""name"": ""MobileCameraController"",
            ""id"": ""d2adef17-4290-4f3c-a998-845459c51035"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""5d3f1d44-d3a3-402e-95e1-f6854fd5ad7e"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""c2a857c1-ea0b-45c2-a2c2-3c181fad2599"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d4450d00-9d72-4c5e-a914-f31afaf48625"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc6b7352-1878-4ee0-86c8-114a187e623f"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MobileCameraController
        m_MobileCameraController = asset.FindActionMap("MobileCameraController", throwIfNotFound: true);
        m_MobileCameraController_Move = m_MobileCameraController.FindAction("Move", throwIfNotFound: true);
        m_MobileCameraController_Look = m_MobileCameraController.FindAction("Look", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MobileCameraController
    private readonly InputActionMap m_MobileCameraController;
    private List<IMobileCameraControllerActions> m_MobileCameraControllerActionsCallbackInterfaces = new List<IMobileCameraControllerActions>();
    private readonly InputAction m_MobileCameraController_Move;
    private readonly InputAction m_MobileCameraController_Look;
    public struct MobileCameraControllerActions
    {
        private @MobileController m_Wrapper;
        public MobileCameraControllerActions(@MobileController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_MobileCameraController_Move;
        public InputAction @Look => m_Wrapper.m_MobileCameraController_Look;
        public InputActionMap Get() { return m_Wrapper.m_MobileCameraController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MobileCameraControllerActions set) { return set.Get(); }
        public void AddCallbacks(IMobileCameraControllerActions instance)
        {
            if (instance == null || m_Wrapper.m_MobileCameraControllerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MobileCameraControllerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
        }

        private void UnregisterCallbacks(IMobileCameraControllerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
        }

        public void RemoveCallbacks(IMobileCameraControllerActions instance)
        {
            if (m_Wrapper.m_MobileCameraControllerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMobileCameraControllerActions instance)
        {
            foreach (var item in m_Wrapper.m_MobileCameraControllerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MobileCameraControllerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MobileCameraControllerActions @MobileCameraController => new MobileCameraControllerActions(this);
    public interface IMobileCameraControllerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
    }
}
